openapi: 3.0.0
info:
  title: supporterz_hackathon_2021 API Document
  description: バックエンド API仕様
  version: '1.0'
  contact:
    name: Takeshi Haga
    email: ritorut18@gmail.com
servers:
  - url: 'http://localhost:1323'
tags:
  - name: setting
    description: 設定事項の出力
  - name: trip
    description: GPS関連
  - name: user
    description: ユーザ関連
paths:
  /user/create:
    post:
      summary: ユーザを登録するAPI
      tags:
        - user
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: string
                  token:
                    type: string
              examples:
                example-1sq:
                  value:
                    user_id: string
                    token: string
      operationId: post-user-create
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_name:
                  type: string
                password:
                  type: string
            examples:
              example-1:
                value:
                  user_name: user3
                  password: password3
          application/xml:
            schema:
              type: object
              properties: {}
        description: API to create user
      description: ユーザを登録するAPI
    parameters: []
  /user/login:
    post:
      summary: ログイン機能API
      tags:
        - user
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: string
                  token:
                    type: string
              examples:
                example-1:
                  value:
                    user_id: c8fed8a1-7e15-4516-838a-14a6bc1f703f
                    token: 4f272392-a679-4a86-ba92-3ffd96c83ae8
      operationId: post-api-user-login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_name:
                  type: string
                password:
                  type: string
            examples:
              example-1:
                value:
                  user_name: ccc
                  password: '333'
      parameters: []
      description: ログイン機能API
    parameters: []
  /api/user/get:
    get:
      summary: ユーザ情報を取得するAPI
      tags:
        - user
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: string
                  user_name:
                    type: string
              examples:
                example-1:
                  value:
                    user_id: c8fed8a1-7e15-4516-838a-14a6bc1f703f
                    user_name: aaa
      operationId: get-user
      parameters:
        - schema:
            type: string
          in: query
          name: user_id
          description: ユーザのID
          required: true
        - schema:
            type: string
          in: header
          name: X-Token
          required: true
      description: ユーザ情報を取得するAPI
    parameters: []
  /api/user/get_trip:
    get:
      summary: 旅の一覧を取得するAPI
      tags:
        - trip
        - user
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  trip_id:
                    type: array
                    items:
                      type: string
              examples:
                example-1:
                  value:
                    trip_id:
                      - string
      operationId: get-user-get_trip
      parameters:
        - schema:
            type: string
          in: query
          name: user_id
          description: ユーザID
          required: true
        - schema:
            type: string
          in: header
          name: X-Token
          required: true
      description: 各ユーザごとに保存してある旅を全件取得するAPI
    parameters: []
  /api/trip/get:
    get:
      summary: 旅情報全体を取得するAPI
      operationId: get-trip-get
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  features:
                    type: array
                    items:
                      type: object
                      properties:
                        type:
                          type: string
                        properties:
                          type: object
                          properties:
                            trip_id:
                              type: string
                            img_url:
                              type: string
                        geometry:
                          type: object
                          properties:
                            type:
                              type: string
                            coordinates:
                              type: array
                              items:
                                type: number
              examples:
                example-1:
                  value:
                    type: FeatureCollection
                    features:
                      - type: Feature
                        properties:
                          trip_id: string
                          img_url: 'http://192.168.0.4:1323/static/<画像の名前>'
                        geometry:
                          type: Point
                          coordinates:
                            - -77.038659
                            - 38.931567
      description: 旅情報全体を取得するAPI
      parameters:
        - schema:
            type: string
          in: query
          name: trip_id
          description: 旅のID
          required: true
        - schema:
            type: string
          in: header
          name: X-Token
          required: true
      tags:
        - trip
    parameters: []
  /api/trip/save:
    post:
      tags:
        - trip
      summary: 旅情報保存API
      description: |
        アップロードされた写真を保存するAPI
      operationId: trip-save
      requestBody:
        description: Request Body
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                imgs:
                  type: array
                  items:
                    type: string
            examples:
              example-1:
                value:
                  user_id: c8fed8a1-7e15-4516-838a-14a6bc1f703f
                  imgs:
                    - string
        required: true
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  trip_id:
                    type: string
              examples:
                example-1:
                  value:
                    trip_id: string
      x-codegen-request-body-name: body
      parameters:
        - schema:
            type: string
          in: header
          name: X-Token
          required: true
    parameters: []
  /api/setting/get:
    get:
      tags:
        - setting
      summary: 設定取得API
      description: |
        設定事項の出力
        TODO: 設定をDBに保存し動的に変えられるようにする
      operationId: get-settings
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  hello:
                    type: string
              examples:
                example-1:
                  value:
                    hello: hello
          headers: {}
      parameters:
        - schema:
            type: string
          in: header
          name: X-Token
          required: true
    parameters: []
  '/api/static/{img_url}':
    get:
      summary: 画像のファイルサーバAPI
      description: |-
        S3に保存した画像を取得するAPI
        返り値はbase64エンコードを文字列にキャストしたもの
      parameters:
        - in: path
          name: img_url
          schema:
            type: string
          description: S3に保存した画像のURL
          required: true
        - schema:
            type: string
          in: header
          name: X-Token
          required: true
      operationId: imgs-get
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                type: string
      tags:
        - setting
    parameters:
      - schema:
          type: string
        name: img_url
        in: path
        required: true
components:
  schemas: {}
  securitySchemes: {}
